server:
  port: 8080

spring:
  application:
    name: plugin-gateway

logging:
  level:
    com.webex.agentic: DEBUG
    io.grpc: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

